### ISSUE TITLE
textBlock "writing-mode" proposal

### ISSUE THREAD

**Issue by ya-araki** [altoxml/schema#12]
It is convenient for CJK users to distinguish direction of text. For example,
writing-mode: horizontal-tb; // YOKO-GAKI for Japanese
writing-mode: vertical-rl; // TATE-GAKI for Japanese

**Comment by cowboyMontana** [comment]
Changed label from 'submitted' to 'discussion'.

**Comment by cowboyMontana** [comment]
Assigned Siang Hock as change request champion.

**Comment by evelienket** [comment]
The following are links to information about the language and text direction discussion that took place in the context of issue 22. It was decided that the discussion in itself is still relevant but no longer to solve issue 22.

https://github.com/altoxml/schema/blob/master/v3/discussion%20of%20ALTO%20language%20support.pdf
https://github.com/altoxml/schema/blob/master/v3/Comparison%20of%20text%20direction%20elements.pdf
https://github.com/altoxml/schema/blob/master/v3/ALTO-language%20support%20discussion%20so%20far-20150601.pdf

**Comment by artunit** [comment]
Doing some housecleaning, the links will still be available in the closed issue.
