### ISSUE TITLE
Provenance for OCRProcessing/Processing and Content

### ISSUE THREAD

**Issue by mittagessen** [altoxml/schema#35]
The current OCRProcessing statement is rather rudimentary in not allowing identifiers for each ProcessingStep and being able to link features in the recognition results to particular steps. For example, in our pipeline we frequently use tesseract's page segmentation with ocropus's recognition, so TextLine elements are sourced from one ProcessingStep and their text content is from another one.

A particular use case is when postprocessing like spell checkers add additional variants to String tags (something we'd like to see also) and it may be unclear if the variant is produced by the recognition engine  itself or the spell checker.

**Comment by cneud** [comment]
Thank you for your feedback/request. The whole processingStepType will be investigated in the light of this, in connection with issues #35, #27, #13. 
Any suggestions or particular use cases are welcome.

**Comment by cneud** [comment]
The changes suggested in #13 should help with this - e.g. adding identifiers to _processingSteps_. What remains to be looked into further is how to record **which elements** have been produced or altered by a particular _processingStep_ - list of ID references?

**Comment by cneud** [comment]
Continued in #39.
