### ISSUE TITLE
Identification of running title

### ISSUE THREAD

**Issue by artunit** [altoxml/schema#50]
[NZ Micrographics](http://www.micrographics.co.nz/) on behalf of [The State Library of NSW](https://www.sl.nsw.gov.au/) has asked for a means of identifying _running title_ in ALTO. For example, "Notable Men of Wales" [here](http://iiif-text-granularity.s3-website-us-east-1.amazonaws.com/NLW_Red_Dragon/img/2062919.jpg). There is some indication in the schema of where a running title is located on the page.
```
<xsd:element name="TopMargin" type="PageSpaceType" minOccurs="0">
  <xsd:annotation>
    <xsd:documentation>
      The area between the top line of print and the upper edge of the leaf. It may contain 
      page number or running title.
    </xsd:documentation>
   </xsd:annotation>
</xsd:element>
```
Perhaps _RunningTitle_ could be a _TextBlockType_?

**Comment by jukervin** [comment]
Starting from version 2.1 there is a possibility to use Tags to annotate things in text. Running title could be marked with StructureTag.

```
......
</Styles>
<Tags>
   <StructureTag ID="RT01" TYPE="Running Title>
</Tags>
.......
<Layout>
   <Page>
     <TopMargin>
         <TextBlock TAGREFS="RT01">
            <TextLine>
              ......
            <TextLine>
         </TextBlock>
     <TopMargin>
     .....
   </Page>
</Layout>
```

**Comment by artunit** [comment]
This sounds like a good approach. Thanks for the example!

**Comment by artunit** [comment]
As per the [minutes of 2018-09-20](/altoxml/board/blob/gh-pages/minutes/2018-09-20%20ALTO%20Board%20Meeting%20Minutes.md), I am closing this issue. The suggested solution has been discussed by the Board and this is an elegant use of Tags. Thank-you jukervin!
