### ISSUE TITLE
Asian language (Japanese, Korean, Chinese) with ruby characters cannot be properly represented in ALTO.

### ISSUE THREAD

**Issue by cowboyMontana** [altoxml/schema#51]

**Comment by mittagessen** [comment]
Aren't those already properly dealt with by Unicode interlinear annotation code points or standoff annotation? Explicit semantic markup isn't part of ALTO right now and introducing it might be a slippery slope into TEI territory.

**Comment by artunit** [comment]
ALTO has had a NamedEntityTag since 2014 so there is some precedent for semantics now. I wonder if the main challenge is that ALTO attempts to support the reconstruct of the original appearance of the object, and that requires some way to render interlinear annotation symbols.  My understanding is that Unicode's provision is rarely implemented and is not intended for markup languages.  The characters can be mapped out with ALTO's glyph support but that introduces other problems. I have a few examples I will add to this issue.

**Comment by mittagessen** [comment]
Wikipedia claims Unicode ruby is not intended for markup languages but the recommendation from the consortium has been withdrawn. I agree it wouldn't be cleanest way to encode it, especially as any OCR engine I know of would recognize it as two separate lines making the feature non-implementable for all practical purposes.

A `RoleTag` would allow simple markup of ruby role but linking multiple elements still isn't provided by any ALTO facility.

**Comment by artunit** [comment]
Yes, I think difficult encodings would get messy very quickly. For example, I don't think it's uncommon in manga to have furigana dots beside ruby characters.

![ruby/furigana](https://github.com/altoxml/documentation/blob/master/misc/ruby_furigana.jpg?raw=true)

I don't think my approach is the right one. Glyphs  can technically capture text that is not typographically part of _String_ while keeping the parts of the text together but the schema currently states that the "glyph elements are in order of the word. Each glyph need to be recorded to built up the whole word sequence.".  The other ripple is that ruby characters are usually in a smaller and sometimes different font. OCR engines would approach approach the text as distinct lines, which can make for nonsensical lines, but it would allow for font variations.  I think linking _TextLine_ elements somehow would be the better solution.

**Comment by artunit** [comment]
This might be an opportunity to use _RoleTag_, which is available for "criteria about function or mission":

```xml
......
</Styles>
<Tags>
   <RoleTag ID="IL01" TYPE="Interlinear">
</Tags>
.......
<TextBlock>
    <TextLine TAGREFS="IL01">
    <TextLine>
</TextBlock>
.....
```
This would not require changing the schema and could also be used for other interlinear text scenarios, such as an _interlinear gloss_.

**Comment by artunit** [comment]
Just to close the loop on this, here is the same example without the _glyph_ element.

```xml
<?xml version="1.0" encoding="utf-8"?>
<alto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns="http://www.loc.gov/standards/alto/ns-v4#" 
  xsi:schemaLocation="http://www.loc.gov/standards/alto/ns-v4# http://www.loc.gov/standards/alto/v4/alto-4-0.xsd" 
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <Tags>
    <RoleTag ID="IL01" TYPE="Interlinear"/>
  </Tags>
  <Layout>
    <Page ID="P1" PHYSICAL_IMG_NR="1" HEIGHT="179" WIDTH="499">
      <PrintSpace ID="P1_PS00001" HPOS="9" VPOS="11" WIDTH="486" HEIGHT="158">
        <TextBlock ID="P1_TB00001" HPOS="9" VPOS="11" WIDTH="486" HEIGHT="158" STYLEREFS="font0">
          <TextLine ID="P1_TL00001" TAGREFS="IL01" HPOS="9" VPOS="11" WIDTH="486" HEIGHT="58">
            <!-- ruby string -->
            <String ID="P1_S00001" CONTENT="こうか〈きどたい" WC="94.254443" BOLD="0" ITALIC="0" UNDERLINED="0" MONOSPACE="0" SERIF="0" SMALLCAPS="0"/>
          </TextLine>
          <TextLine ID="P1_TL00002" HPOS="9" VPOS="11" WIDTH="486" HEIGHT="96">
            <!-- start of string proper -->
            <String ID="P1_S00002" CONTENT="攻殻機動隊" WC="94.254443" BOLD="0" ITALIC="0" UNDERLINED="0" MONOSPACE="0" SERIF="0" SMALLCAPS="0"/>
          </TextLine>
        </TextBlock>
      </PrintSpace>
    </Page>
  </Layout>
</alto>
```
This approach would also be an option for interlinear text.

![ruby](https://raw.githubusercontent.com/altoxml/board/gh-pages/misc/interlinear_text.jpg)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<alto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns="http://www.loc.gov/standards/alto/ns-v4#" 
  xsi:schemaLocation="http://www.loc.gov/standards/alto/ns-v4# http://www.loc.gov/standards/alto/v4/alto-4-0.xsd" 
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <Tags>
    <RoleTag ID="IL01" TYPE="Interlinear"/>
  </Tags>
  <Layout>
    <Page WIDTH="455" HEIGHT="56" PHYSICAL_IMG_NR="0" ID="page_0">
      <PrintSpace HPOS="0" VPOS="0" WIDTH="455" HEIGHT="56">
        <TextBlock ID="block_0" HPOS="6" VPOS="12" WIDTH="441" HEIGHT="34">
          <TextLine ID="line_0" HPOS="6" VPOS="12" WIDTH="385" HEIGHT="15">
            <String ID="string_0" HPOS="6" VPOS="12" WIDTH="16" HEIGHT="12" WC="0.67" CONTENT="35"/>
            <String ID="string_1" HPOS="65" VPOS="12" WIDTH="26" HEIGHT="12" WC="0.64" CONTENT="But"/>
            <String ID="string_2" HPOS="96" VPOS="12" WIDTH="78" HEIGHT="15" WC="0.64" CONTENT="nathelees,"/>
            <String ID="string_3" HPOS="180" VPOS="12" WIDTH="30" HEIGHT="12" WC="0.91" CONTENT="whil"/>
            <String ID="string_4" HPOS="217" VPOS="12" WIDTH="2" HEIGHT="12" WC="0.74" CONTENT="|"/>
            <String ID="string_5" HPOS="226" VPOS="12" WIDTH="35" HEIGHT="12" WC="0.71" CONTENT="have"/>
            <String ID="string_6" HPOS="266" VPOS="12" WIDTH="37" HEIGHT="15" WC="0.71" CONTENT="tyme"/>
            <String ID="string_7" HPOS="309" VPOS="12" WIDTH="27" HEIGHT="12" WC="0.91" CONTENT="and"/>
            <String ID="string_8" HPOS="343" VPOS="15" WIDTH="48" HEIGHT="12" WC="0.81" CONTENT="space,"/>
          </TextLine>
          <TextLine ID="line_1" TAGREFS="IL01" HPOS="83" VPOS="31" WIDTH="364" HEIGHT="15">
            <String ID="string_9" HPOS="83" VPOS="31" WIDTH="23" HEIGHT="12" WC="0.92" CONTENT="But"/>
            <String ID="string_10" HPOS="112" VPOS="31" WIDTH="86" HEIGHT="12" WC="0.66" CONTENT="nonetheless,"/>
            <String ID="string_11" HPOS="208" VPOS="31" WIDTH="36" HEIGHT="12" WC="0.92" CONTENT="while"/>
            <String ID="string_12" HPOS="250" VPOS="31" WIDTH="2" HEIGHT="12" WC="0.56" CONTENT="I"/>
            <String ID="string_13" HPOS="259" VPOS="31" WIDTH="33" HEIGHT="12" WC="0.92" CONTENT="have"/>
            <String ID="string_14" HPOS="298" VPOS="31" WIDTH="30" HEIGHT="12" WC="0.84" CONTENT="time"/>
            <String ID="string_15" HPOS="334" VPOS="31" WIDTH="25" HEIGHT="12" WC="0.84" CONTENT="and"/>
            <String ID="string_16" HPOS="365" VPOS="31" WIDTH="82" HEIGHT="15" WC="0.48" CONTENT="opportunity,"/>
          </TextLine>
        </TextBlock>
      </PrintSpace>
    </Page>
  </Layout>
</alto>
```

**Comment by artunit** [comment]
Whoops, didn't mean to close!

**Comment by artunit** [comment]
In an effort to keep ahead of schema issues, ones without a direct schema implication will be closed if deemed to be no longer active or if the discussion has gone full circle. They can be reopened if requested.
