### ISSUE TITLE
ALTO 4.0: adaptation of "Processing" substructure

### ISSUE THREAD

**Issue by Jo-CCS** [altoxml/schema#52]
As outlined on the last conference call it was figured out by CCS development team an issue on the new "Processing" node defintion on implementing the new schema version to our product.

The current defined structure is referencing from "Processing" node the complexType "processingStepType":
![alto_4-0](https://user-images.githubusercontent.com/6001497/45879096-c3a44e00-bd92-11e8-9835-f474420c8195.jpg)

Intended was the reference of the complexType "processingType" with the classification of the processing operation:
![alto_4-0_mod](https://user-images.githubusercontent.com/6001497/45879212-2564b800-bd93-11e8-9991-47bd21891d89.png)
This defined type is not referenced now at all even existing in the schema.

The proposal is just to add the classification missed now as element parallel to the other information  which keeps the hierarchy flat as it is now and does not cause a big issue to add this classification as additional property to the "processingStepType" instead of the additional node level like this:

![alto_4-1_prop](https://user-images.githubusercontent.com/6001497/45880163-90fc5480-bd96-11e8-8e42-393d74aadf1f.png)

This will remain compatible to 4-0 and will just allow the classification as it was intended from the discussion to cluster the operations commonly if applicable.

Finally also Jukka proposed to add the reference to the processing steps elements not just on page level than also to the sub structures to outline e.g. strings reprocessed with additional operations.

The modified schema result I will upload now as 4-1 (draft) as proposal result for review.

**Comment by Jo-CCS** [comment]
On generation of the 4-1 draft schema I ran into naming collision already noted on the pre-discussion with Jukka on this issue evaluation.
Due to this I renamed now the "processingStepType" to "processingCategory" to have the complexType naming not defined "processingStepTypeType" or similar confusing definitions.
Please review and comment - proposal available here:
https://github.com/altoxml/schema/blob/master/v4/alto-4-1_draft.xsd

**Comment by artunit** [comment]
Looks good, Jo, thanks for all the work on this.

**Comment by artunit** [comment]
ACCEPT

**Comment by Jo-CCS** [comment]
ACCEPT

**Comment by jukervin** [comment]
ACCEPT

**Comment by cneud** [comment]
ACCEPT

Am Mi., 10. Apr. 2019 um 08:02 Uhr schrieb Jukka Kervinen <
notifications@github.com>:

**Comment by Ra1phM** [comment]
ACCEPT

**Comment by rajubln** [comment]
ACCEPT

**Comment by MatthewThomasMiller** [comment]
ACCEPT

**Comment by evelienket** [comment]
ACCEPT

**Comment by hanyelsawy** [comment]
ACCEPT

**Comment by ntra00** [comment]
ACCEPT

**Comment by artunit** [comment]
ACCEPT from Brian, Cally, and Jean-Philippe (by email) - changing status to accepted.

**Comment by splet** [comment]
ACCEPT

**Comment by rajubln** [comment]
ACCEPT

**Comment by Jo-CCS** [comment]
Fix included in v4.1, released June 2019

**Comment by MatthewThomasMiller** [comment]
ACCEPT

*____________________________________________*
*Matthew Thomas Miller, Ph.D. (Pronouns: He, Him, His)*
Assistant Professor, Persian Literature & Digital Humanities, Roshan
Institute for Persian Studies <https://sllc.umd.edu/persian>
Associate Director, Roshan Initiative in Persian Digital Humanities
(PersDig@UMD) <http://persdig.umd.edu/>
Affiliate, Maryland Institute for Technology in the Humanities (MITH)
<https://mith.umd.edu/>
University of Maryland, College Park
Professional website <http://www.matthewthomasmiller.com/> | Humanities
Commons Page <https://hcommons.org/members/mtmiller/> | Open Islamicate
Texts Initiative (OpenITI) <https://openiti.github.io/> | Persian
Manuscript Initiative (PMI) <http://www.persianmanuscript.org/>
