### ISSUE TITLE
Line, Rectangle, Polygon and Image questions

### ISSUE THREAD

**Issue by silviu22** [altoxml/schema#58]
Do you have examples of how to represent lines, rectangles and images?

It looks to me that we can have only horizontal/vertical lines. Is it supposed to be something like this:

<GraphicalElement>
  <Line ID="Line_01" WIDTH="50" HEIGHT="1" VPOS="20" HPOS="5" STYLEREFS="Line_style_0" />
</GraphicalElement>

<GraphicalElement>
  <Line ID="Line_02" WIDTH="1" HEIGHT="30" VPOS="30" HPOS="10" STYLEREFS="Line_style_1" /> 
</GraphicalElement>

Can I specify the line color in Line_style_0? It is pretty limiting if all lines are assumed to be black color.

How does one specify a diagonal line, from (10, 10) to (20, 30)?

Is this how you represent a rectangle:
<GraphicalElement>
  <Rectangle ID="Rect_01" WIDTH="50" HEIGHT="40" VPOS="20" HPOS="20" STYLEREFS="Rect_style_0" />  
</GraphicalElement>

To properly specify a rectangle, you need line width, line color, background color? How do I include these in "Rect_style_0"? If you don't specify them in the Alto documentation, people will start using their own attributes.

I do not see a background color for text. So theoretically, one could specify text with a yellow background as text and a rectangle in the same place as the text, where the rectangle line width is 0 and the fill color is the desired text highlight color (say yellow).

Are polygons always closed shapes, in which the last line is a line back from the last point to the first point? Can I draw something like a rectangle without one of the edges?

If polygons don't have to be closed, a diagonal line could be a polygon with two points.

Also, can we have some examples of images? Is this an valid example of an image:
<Illustration TYPE="image" FILEID="http://www.webdomain.com/image1.jpg" />

How about embedded images? Is this allowed?
<Illustration TYPE="image" 
  FILEID="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAA..."
/>

Basically, I am trying to represent these objects:
![Objects](https://user-images.githubusercontent.com/48599576/54451269-d9367700-4728-11e9-92f6-131c4f679e52.JPG)

**Comment by artunit** [comment]
ALTO describes OCR output, you can get a sense of how the shapes are applied to text [here](http://altoxml.github.io/documentation/use-cases/shape/ALTO_shape_usecases.html). There is provision for specifying font colour, and illustrations and graphics can be delimited, but ALTO is mostly focused on text. I think you can specify background colours in the [PAGE](https://www.primaresearch.org/schema/PAGE/gts/pagecontent/2018-07-15/pagecontent.xsd) format and it might be a better fit for literal shapes.

**Comment by silviu22** [comment]
Thank you for the clarifications. It looks like the shapes (polygon, ellipse) were added to describe text in non-rectangular areas. Is that correct?

So were these shapes added to describe text in non-rectangular area rather than to provide a way to draw ellipses or polygons? In the specifications, the shapes seems to be intended mainly to describe blocks of text rather than be blocks themselves. The shape examples listed in your link are all for text filling a certain shape. 

So is it possible to have an ellipse GraphicalElement?

**Comment by artunit** [comment]
The shapes are for blocks which can contain either text or illustrations. I am not sure I am understanding the question but they would not be drawing shapes if that helps.

**Comment by artunit** [comment]
In an effort to keep ahead of schema issues, ones without a direct schema implication will be closed if deemed to be no longer active or if the discussion has gone full circle. They can be reopened if requested.
