### ISSUE TITLE
JSON equivalent / transformation for ALTO standard ( jALTO? )

### ISSUE THREAD

**Issue by Jo-CCS** [altoxml/schema#60]
Based on todays ALTO board call I want to note down the topic about verification for definition of an ALTO equivalent JSON format definition.
Question is what is needed and how to proceed to define such standardized format to be able to convert ALTO files, which get bigger in the latest extensions of glyph alternatives as well in the current spotted context of Handwriting and description for handwritten material.

As JSON format is much less data intensive format and with the extensions for plenty of variants for characters and words the data become anyway human-unreadable it would make sense to define a standardized way of conversation and in case of format specific conversion issues those should be commonly defined to keep global data exchange possible.

**Comment by artunit** [comment]
In an effort to keep ahead of schema issues, ones without a direct schema implication will be closed if deemed to be no longer active or if the discussion has gone full circle. They can be reopened if requested.
