### ISSUE TITLE
FONTSTYLE: add "strikethrough" to list of allowed values

### ISSUE THREAD

**Issue by janvonde** [altoxml/schema#61]
We would like to mark crossed out words in ALTO files using the FONTSTYLE attribute but there is no option in the list of allowed elements. I suggest adding "strikethrough" or similar there.

**Comment by artunit** [comment]
Just to be sure I am capturing this properly, this would entail changing the _fontStylesType_ as follows:

```
<xsd:simpleType name="fontStylesType">
   <xsd:annotation>
      <xsd:documentation>List of any combination of font styles</xsd:documentation>
   </xsd:annotation>
   <xsd:restriction>
      <xsd:simpleType>
         <xsd:list>
            <xsd:simpleType>
               <xsd:restriction base="xsd:string">
                  <xsd:enumeration value="bold"/>
                  <xsd:enumeration value="italics"/>
                  <xsd:enumeration value="subscript"/>
                  <xsd:enumeration value="superscript"/>
                  <xsd:enumeration value="smallcaps"/>
                  <xsd:enumeration value="strikethrough"/>
                  <xsd:enumeration value="underline"/>
               </xsd:restriction>
         </xsd:simpleType>
         </xsd:list>
      </xsd:simpleType>
      <xsd:minLength value="1"/>
   </xsd:restriction>
</xsd:simpleType>
```
I don't think there would be any objection to this change but I will flag it for the next Board meeting.

**Comment by janvonde** [comment]
Thank you! :smile:

**Comment by cneud** [comment]
Considering the addition above, this might present an opportunity to check whether there are any further demands for fontStyle attributes we should/would want to add in ALTO, cf. in comparison to what is commonly used in TEI (e.g. "handwritten", "letter-spacing", ...).

**Comment by janvonde** [comment]
Can I ask about the current state of the discussion?

**Comment by artunit** [comment]
This was discussed at the [2020-02-14 Board Meeting](https://github.com/altoxml/board/blob/gh-pages/minutes/2020/2020-02-14%20ALTO%20Board%20Meeting%20Minutes.md) and there was general agreement for adding to the list of allowed values. There was a sense that it would a good opportunity to put together a list of additional font styles that are used in other XML schema and that should appear here. I will follow up on this, we had planned for an in-person Board meeting on April 22 as part of the the [Impresso](https://impresso.github.io/eldorado/) conference, and I am hoping we can arrange for a virtual equivalent if the conference goes ahead online.

**Comment by artunit** [comment]
As per the discussion on issue #65 and the opportunity of a new revision to the schema, this issue is open for voting by Board Members, using the proposed syntax in the comment.

**Comment by artunit** [comment]
ACCEPT

**Comment by ntra00** [comment]
ACCEPT

**Comment by cneud** [comment]
ACCEPT

**Comment by splet** [comment]
ACCEPT

**Comment by hanyelsawy** [comment]
ACCEPT

**Comment by cipriandinu** [comment]
ACCEPT

**Comment by cowboyMontana** [comment]
ACCEPT

**Comment by jukervin** [comment]
ACCEPT

**Comment by callylaw** [comment]
Ok

**Comment by bkgeig** [comment]
ACCEPT

**Comment by artunit** [comment]
Added in [v4.2](/altoxml/schema/blob/master/v4/alto-4-2.xsd), released August 2020.
