### ISSUE TITLE
Should FONTSIZE be optional?

### ISSUE THREAD

**Issue by chris1010010** [altoxml/schema#64]
At the moment FONTSIZE in TextStyle is required.
If the font size is not available, no other style attributes can be used. Is that by design?
For example, it is not possible to store FONTCOLOR unless also FONTSIZE is provided.

**Comment by artunit** [comment]
Thanks for raising this - I have put it on the [agenda for the upcoming 2019-12-13 Board meeting](https://github.com/altoxml/board/blob/gh-pages/agenda/2019-12-13%20ALTO%20Board%20Meeting%20Agenda.md).

**Comment by artunit** [comment]
As per the [2019-12-13 Board meeting](https://github.com/altoxml/board/blob/gh-pages/minutes/2019-12-13%20ALTO%20Board%20Meeting%20Minutes.md), it is proposed to change FONTSIZE from _required_ to _optional_, i.e.:

```
<xsd:attribute name="FONTSIZE" type="xsd:float" use="required">
  <xsd:annotation>
    <xsd:documentation>The font size, in points (1/72 of an inch).</xsd:documentation>
  </xsd:annotation>
</xsd:attribute>
``` 

to:

```
<xsd:attribute name="FONTSIZE" type="xsd:float" use="optional">
  <xsd:annotation>
    <xsd:documentation>The font size, in points (1/72 of an inch).</xsd:documentation>
  </xsd:annotation>
</xsd:attribute>
```

**Comment by artunit** [comment]
ACCEPT

**Comment by cipriandinu** [comment]
ACCEPT

**Comment by splet** [comment]
ACCEPT

**Comment by cneud** [comment]
ACCEPT

**Comment by Ra1phM** [comment]
ACCEPT

**Comment by ntra00** [comment]
ACCEPT

**Comment by bkgeig** [comment]
ACCEPT

**Comment by cowboyMontana** [comment]
ACCEPT

**Comment by jukervin** [comment]
ACCEPT

**Comment by rajubln** [comment]
ACCEPT

**Comment by artunit** [comment]
Added in [v4.2](/altoxml/schema/blob/master/v4/alto-4-2.xsd), released August 2020.
