### ISSUE TITLE
Proposed schema revision

### ISSUE THREAD

**Issue by artunit** [altoxml/schema#65]
At the [2020-06-12 ALTO Board Meeting](/altoxml/board/blob/gh-pages/minutes/2020/2020-06-12%20ALTO%20Board%20Meeting%20Minutes.md), it was agreed that a [proposed revision to the ALTO schema](/altoxml/schema/blob/master/v4/alto-4-2.xsd) would be made available for comment. The proposed changes are as follows:

   * Change schema version to 4.2
   * Change BASELINE to accommodate a list of points in addition to a single point - see [schema issue #32](/altoxml/schema/issues/32)
   * Make FONTSIZE optional - see [schema issue #64](/altoxml/schema/issues/64)

This issue will be used to track comments and will be closed when the version is published.

**Comment by cneud** [comment]
There was a [question](https://twitter.com/pregopresto/status/1280896573933785090?s=20) whether #61 could still be included with this release as well.

**Comment by artunit** [comment]
We could definitely include the one change suggested in the issue #61, i.e., "add 'strikethrough' to the list of allowed values", and leave the notion of a definitive list for later and/or as requested. I will set the issue up for a vote, thanks for flagging this.

**Comment by artunit** [comment]
Addressed in [v4.2](/altoxml/schema/blob/master/v4/alto-4-2.xsd), released August 2020.
