### ISSUE TITLE
Storing detected languages 

### ISSUE THREAD

**Issue by jmokoistinen** [altoxml/schema#66]
Hi,

Wondering which would be best way to store information of detected language(s) and their point difference. The information is to be used by UI to filter pages by their language(s).

@jukervin commented that possibly currently only way is to use Page element QUALITY_DETAIL attribute (string)

Any other ideas? Thanks!

**Comment by jukervin** [comment]
I didn't see a proper / elegant way to store the information within the schema.

- Processing doesn't have a element to record processing outcome information or note. Information would have to be stored in processingStepDescription or processingStepSettings.
- Page or PrintSpace/Margins don't have TAGREFS for using OtherTag and the information would need to apply to whole page.
- LANG (xsd:language) is available in TextBlocks and below and can only store one language without additional information.

**Comment by artunit** [comment]
@bertsky's [comment](https://github.com/altoxml/schema/issues/55#issuecomment-511056317) on [Add LANG and ROTATION attributes to Page element](https://github.com/altoxml/schema/issues/55) might be considered here. PAGE uses `xsd:list itemType="xsd:language"` to allow a comma-delimited list, and this approach could be considered for ALTO.

**Comment by cipriandinu** [comment]
ACCEPT

**Comment by cneud** [comment]
ACCEPT

**Comment by ntra00** [comment]
ACCEPT

**Comment by Haighton** [comment]
ACCEPT

**Comment by acpopat** [comment]
ACCEPT

**Comment by cowboyMontana** [comment]
ACCEPT

**Comment by c-sebastien** [comment]
ACCEPT
