### ISSUE TITLE
Clarify implicit reading order

### ISSUE THREAD

**Issue by mittagessen** [altoxml/schema#68]
There are currently no mentions of reading order anywhere in the standard and most people treat the sequence of elements as the order these elements should be read, e.g. the n-th `<String>` in a `<TextLine>` is the n-th word a human reader would read in that line. 
 
Apparently this isn't evident to everyone out there. [These](https://twitter.com/tillgrallert/status/1369761658437054464) tweets document that Transkribus's ALTO output sorts `<String>` elements from left to right which causes an inversion for RTL text. We should probably clarify that `<TextLine>/<String>/<Glyph>` are to be ordered in a way that corresponds to the text flow.

**Comment by cneud** [comment]
Thank you Ben for chiming in and raising the issue here! I saw the tweets but you beat me to it ;) 

There was some discussion on making this more explicit previously, the outcomes of which are captured here https://github.com/altoxml/schema/issues/12#issuecomment-113184844, but eventually no changes to the schema were made. Maybe now is a good time to revisit this.

**Comment by mittagessen** [comment]
Yes, I'm aware of previous discussions regarding reading order but these require a larger overhaul of the object ordering notation as quite a few documents would need multiple reading orders and other 'advanced' features.

This is mostly about putting an explanatory note in some supplementary material that textual elements are not some amorphous cloud but their sequence represents a valid text flow, i.e. clarifying how all but one software currently serializes into ALTO. No actual changes to the schema needed.

**Comment by artunit** [comment]
Adding a link to [issue 69](https://github.com/altoxml/schema/issues/69) (Confidence value for Layout detection of elements) here.

**Comment by cipriandinu** [comment]
ACCEPT

**Comment by cneud** [comment]
ACCEPT

**Comment by artunit** [comment]
ACCEPT

**Comment by cowboyMontana** [comment]
ACCEPT

**Comment by callylaw** [comment]
ACCEPT

**Comment by Haighton** [comment]
ACCEPT

**Comment by cowboyMontana** [comment]
ACCEPT

**Comment by Ra1phM** [comment]
ACCEPT

**Comment by ntra00** [comment]
ACCEPT

**Comment by JLoitzenbauer-CRKN** [comment]
ACCEPT

**Comment by bkgeig** [comment]
ACCEPT

**Comment by rajubln** [comment]
ACCEPT

**Comment by acpopat** [comment]
ACCEPT

**Comment by cipriandinu** [comment]
Published in v4.3
