### ISSUE TITLE
Support for script in addition to language

### ISSUE THREAD

**Issue by kba** [altoxml/schema#70]
With the `@LANG` attribute, ISO 639-3 codes can be used to express the language of the String, TextLine, TextBlock, and at some point PAGE (#55). But what about the script the text is written in? With a `@SCRIPT` attribute in all places where `@LANG` is allowed, one could express the script e.,g. as a 4-letter ISO 15924 code. PAGE-XML has support for both, [roughly representing](https://github.com/PRImA-Research-Lab/PAGE-XML/issues/27) ISO 639 and ISO 15924.

**Comment by mittagessen** [comment]
ISO 15924 is a horrible mess and not a good place to start. The 'granularity' of the descriptors varies widely and their semantics are unclear, e.g. there exist separate identifiers for the different styles of Syriac but all Arabic scripts share one identifier. Free text fields might be better in the absence of a good standard.

**Comment by artunit** [comment]
As per the [2021-04-29 Board Meeting](/altoxml/board/blob/gh-pages/minutes/2021/2021-04-29%20ALTO%20Board%20Meeting%20Minutes.md), I am adding a link to [BCP 47](https://en.wikipedia.org/wiki/IETF_language_tag), which might be one possible approach for script identification, based on positive experience at Google.

**Comment by cipriandinu** [comment]
I think that xsd:language can cover also the script topic. According with xsd:language definition, this is the set of language codes defined by RFC 1766. RFC 1766 (https://www.rfc-editor.org/rfc/pdfrfc/rfc1766.txt.pdf) defines the language as:

Language-Tag = Primary-tag *( "-" Subtag )
Primary-tag = 1*8ALPHA
Subtag = 1*8ALPHA

where first subtag is:

 - All 2-letter codes are interpreted as ISO 3166 alpha-2
 country codes denoting the area in which the language is
 used.
 - Codes of 3 to 8 letters may be registered with the IANA by
 anyone who feels a need for it, according to the rules in
 chapter 5 of this document.
 The information in the subtag may for instance be:
 - Country identification, such as en-US (this usage is
 described in ISO 639)
 - Dialect or variant information, such as no-nynorsk or en-
 cockney
 - Languages not listed in ISO 639 that are not variants of
 any listed language, which can be registered with the i-
 prefix, such as i-cherokee
 **- Script variations, such as az-arabic and az-cyrillic**

The list of registered codes cand be found here: 

https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

Using this is possible to encode also the scripts - there are defined about 212 possible scripts that can be used as subtag

Changing to a different standard probably will create back-compatibility issues.

**Comment by cipriandinu** [comment]
After discussion on ALTO board, I propose to close this item, based on the previous comment. @kba please review and give us your feedback. I will set the topic for voting (ACCEPT means agree to close the item)

**Comment by kba** [comment]
You're right, `xsd:language` is flexible enough to express both. We will use the RFC 1766 mechanics for language/script. That should also support subtyping Arabic as @mittagessen wanted AFAICT.

**Comment by kba** [comment]
ACCEPT

**Comment by cipriandinu** [comment]
ACCEPT

**Comment by cneud** [comment]
ACCEPT

**Comment by ntra00** [comment]
ACCEPT

**Comment by Haighton** [comment]
ACCEPT

**Comment by acpopat** [comment]
ACCEPT

**Comment by cipriandinu** [comment]
@kba it looks like in fact I was a bit outdated, the last definition of xsd:language refers BCP47, that replaces older standards. But from ALTO perspective we use xsd:language and this alows to cover any specific script as well (this was the original topic) - either using BCP47 or much older RFC1776 mechanism.

**Comment by cowboyMontana** [comment]
ACCEPT

**Comment by JLoitzenbauer-CRKN** [comment]
ACCEPT

**Comment by callylaw** [comment]
ACCEPT

**Comment by hanyelsawy** [comment]
ACCEPT

**Comment by Haighton** [comment]
ACCEPT

**Comment by c-sebastien** [comment]
ACCEPT

**Comment by jukervin** [comment]
ACCEPT

**Comment by ntra00** [comment]
ACCEPT

**Comment by cipriandinu** [comment]
Closed based on existing votes
