### ISSUE TITLE
Typo processing{,Step}Type and in documentation for GC attribute

### ISSUE THREAD

**Issue by kba** [altoxml/schema#71]
https://github.com/altoxml/schema/blob/831adab03d0b20d3d6a220f082ce496a18caef12/v4/alto-4-2.xsd#L728

`processingType` should `processingStepType` in the description I think.

**Comment by artunit** [comment]
Good catch! I will pass this by the Board at our upcoming meeting.

**Comment by artunit** [comment]
As per the [2021-04-29 Board Meeting](/altoxml/board/blob/gh-pages/minutes/2021/2021-04-29%20ALTO%20Board%20Meeting%20Minutes.md), this fix, as well as the typo here:

https://github.com/altoxml/schema/blob/831adab03d0b20d3d6a220f082ce496a18caef12/v4/alto-4-2.xsd#L1047

where `variant` will be changed to `glyph`, will be part of the next release of the schema. The issue name will also be changed to reflect both changes.

**Comment by cneud** [comment]
ACCEPT

**Comment by cipriandinu** [comment]
ACCEPT

**Comment by ntra00** [comment]
ACCEPT

**Comment by cowboyMontana** [comment]
ACCEPT

**Comment by jukervin** [comment]
ACCEPT

**Comment by callylaw** [comment]
ACCEPT

**Comment by Haighton** [comment]
ACCEPT

**Comment by Ra1phM** [comment]
ACCEPT

**Comment by JLoitzenbauer-CRKN** [comment]
ACCEPT

**Comment by SebastienC-BnF** [comment]
ACCEPT

**Comment by bkgeig** [comment]
ACCEPT

**Comment by rajubln** [comment]
ACCEPT

**Comment by acpopat** [comment]
ACCEPT

**Comment by cipriandinu** [comment]
Published in v4.3
