### ISSUE TITLE
Support for encoding script direction 

### ISSUE THREAD

**Issue by mittagessen** [altoxml/schema#73]
ALTO lacks a way to encode the reading direction of the principal script in a document. While this is mostly unproblematic for simple texts in a single script there are multiple reasons to encode text direction explicitly:
* Hand-corrected texts in RTL scripts will most likely be produced in an environment that has the base text direction set to RTL. Processing of these texts in a base direction LTR environment will cause reshuffling of weak LTR elements like numbers, punctuation, parentheses, etc. The same is true when displaying an OCRed (almost exclusively base LTR) in an RTL environment. This is a sample of the latter: 
![Sample of base direction LTR OCRed text in RTL environment](https://files.gitter.im/605a15db6da037398476bbc1/Y9H2/image.png)
* Vertical writing (top-to-bottom and bottom-to-top) usually requires different visualization to rotated writing in horizontal scripts.

I realize that these issues are somewhat independent of each other and a text in a principal RTL script might not actually be in RTL base direction. For simplicity's sake I would nevertheless treat them the same, primarily as any editing will most likely occur in the requisite base text direction environment and I'm not entirely sure if lossless conversion between the two base directions is actually possible.

**Comment by artunit** [comment]
Where do you think this would best fit in the schema? For example, would it make sense as an attribute, e.g. _direction_, of the _String_ element?

**Comment by mittagessen** [comment]
Personally, I would add an attribute both the a document level (declaring a principal document direction) and also allow overriding the document-wide setting on block and string element-level (for mixed documents). 

The semantics become a bit tricky in multi-script documents containing e.g. exclusively Latin and exclusively Arabic text blocks. Human-corrected ground truth will most likely be prepared in a single base direction but that would require setting the *wrong* direction on some blocks. We could have a *bidi_direction* attribute for global BiDi base text direction and *direction* for marking the actual text direction on all levels.  On the other hand, it is nowhere specified that ALTO documents are in Unicode in the first place.

**Comment by cneud** [comment]
ACCEPT

**Comment by cipriandinu** [comment]
ACCEPT

**Comment by artunit** [comment]
ACCEPT

**Comment by cowboyMontana** [comment]
ACCEPT

**Comment by callylaw** [comment]
ACCEPT

**Comment by jukervin** [comment]
ACCEPT

**Comment by Haighton** [comment]
ACCEPT

**Comment by Ra1phM** [comment]
ACCEPT

**Comment by ntra00** [comment]
ACCEPT

**Comment by JLoitzenbauer-CRKN** [comment]
ACCEPT

**Comment by SebastienC-BnF** [comment]
ACCEPT

**Comment by rajubln** [comment]
ACCEPT

**Comment by acpopat** [comment]
ACCEPT

**Comment by cipriandinu** [comment]
Published in v4.3
